module.exports = [
  {
    name: 'Structured Wool Blazer',
    brand: 'The Row',
    type: 'outerwear',
    color: 'charcoal',
    silhouette: 'tailored',
    aestheticTags: ['minimalist', 'luxury', 'monochrome', 'editorial'],
    imageUrl: 'https://picsum.photos/seed/shootai-blazer/600/800',
    productUrl: 'https://www.ssense.com/en-us/women/product/the-row/structured-wool-blazer',
    price: 1890,
    currency: 'USD',
  },
  {
    name: 'Neon Mesh Bodysuit',
    brand: 'Mugler',
    type: 'top',
    color: 'neon-green',
    silhouette: 'bodycon',
    aestheticTags: ['cyberpunk', 'futuristic', 'neon', 'high-contrast', 'urban'],
    imageUrl: 'https://picsum.photos/seed/neon-mesh-bodysuit.jpg/600/800',
    productUrl: 'https://www.ssense.com/en-us/women/product/mugler/neon-mesh-bodysuit',
    price: 720,
    currency: 'USD',
  },
  {
    name: 'Chrome Metallic Trousers',
    brand: 'Rick Owens',
    type: 'bottom',
    color: 'chrome',
    silhouette: 'wide-leg',
    aestheticTags: ['futuristic', 'avant-garde', 'high-contrast', 'urban'],
    imageUrl: 'https://picsum.photos/seed/chrome-metallic-trousers.jpg/600/800',
    productUrl: 'https://www.farfetch.com/shopping/women/rick-owens-chrome-trousers',
    price: 1120,
    currency: 'USD',
  },
  {
    name: 'Oversized Graphic Hoodie',
    brand: 'Balenciaga',
    type: 'top',
    color: 'black',
    silhouette: 'oversized',
    aestheticTags: ['streetwear', 'urban', 'monochrome', 'high-contrast'],
    imageUrl: 'https://picsum.photos/seed/oversized-graphic-hoodie.jpg/600/800',
    productUrl: 'https://www.ssense.com/en-us/men/product/balenciaga/oversized-graphic-hoodie',
    price: 950,
    currency: 'USD',
  },
  {
    name: 'Silk Slip Midi Dress',
    brand: 'Bottega Veneta',
    type: 'dress',
    color: 'cream',
    silhouette: 'flowing',
    aestheticTags: ['minimalist', 'luxury', 'soft-pastel', 'editorial'],
    imageUrl: 'https://picsum.photos/seed/silk-slip-midi-dress.jpg/600/800',
    productUrl: 'https://www.farfetch.com/shopping/women/bottega-veneta-silk-slip-dress',
    price: 2100,
    currency: 'USD',
  },
  {
    name: 'Deconstructed Leather Jacket',
    brand: 'Maison Margiela',
    type: 'outerwear',
    color: 'black',
    silhouette: 'tailored',
    aestheticTags: ['avant-garde', 'monochrome', 'editorial', 'urban'],
    imageUrl: 'https://picsum.photos/seed/deconstructed-leather-jacket.jpg/600/800',
    productUrl: 'https://www.ssense.com/en-us/women/product/maison-margiela/leather-jacket',
    price: 3400,
    currency: 'USD',
  },
  {
    name: 'Cargo Utility Pants',
    brand: 'Off-White',
    type: 'bottom',
    color: 'olive',
    silhouette: 'relaxed',
    aestheticTags: ['streetwear', 'urban', 'utility'],
    imageUrl: 'https://picsum.photos/seed/cargo-utility-pants.jpg/600/800',
    productUrl: 'https://www.farfetch.com/shopping/men/off-white-cargo-pants',
    price: 680,
    currency: 'USD',
  },
  {
    name: 'Pastel Knit Cardigan',
    brand: 'Jacquemus',
    type: 'top',
    color: 'lilac',
    silhouette: 'cropped',
    aestheticTags: ['soft-pastel', 'minimalist', 'bohemian'],
    imageUrl: 'https://picsum.photos/seed/pastel-knit-cardigan.jpg/600/800',
    productUrl: 'https://www.ssense.com/en-us/women/product/jacquemus/pastel-knit-cardigan',
    price: 540,
    currency: 'USD',
  },
  {
    name: 'Vintage Wash Denim Jacket',
    brand: 'Acne Studios',
    type: 'outerwear',
    color: 'indigo',
    silhouette: 'boxy',
    aestheticTags: ['vintage', 'streetwear', 'urban'],
    imageUrl: 'https://picsum.photos/seed/vintage-wash-denim-jacket.jpg/600/800',
    productUrl: 'https://www.farfetch.com/shopping/women/acne-studios-denim-jacket',
    price: 490,
    currency: 'USD',
  },
  {
    name: 'Holographic Platform Boots',
    brand: 'Rombaut',
    type: 'footwear',
    color: 'holographic',
    silhouette: 'chunky',
    aestheticTags: ['cyberpunk', 'futuristic', 'neon', 'avant-garde'],
    imageUrl: 'https://picsum.photos/seed/holographic-platform-boots.jpg/600/800',
    productUrl: 'https://www.ssense.com/en-us/women/product/rombaut/holographic-boots',
    price: 610,
    currency: 'USD',
  },
  {
    name: 'Minimal Leather Loafers',
    brand: 'Prada',
    type: 'footwear',
    color: 'black',
    silhouette: 'slim',
    aestheticTags: ['minimalist', 'luxury', 'monochrome'],
    imageUrl: 'https://picsum.photos/seed/minimal-leather-loafers.jpg/600/800',
    productUrl: 'https://www.farfetch.com/shopping/women/prada-leather-loafers',
    price: 990,
    currency: 'USD',
  },
  {
    name: 'Flowing Bohemian Maxi Skirt',
    brand: 'Zimmermann',
    type: 'bottom',
    color: 'terracotta',
    silhouette: 'flowing',
    aestheticTags: ['bohemian', 'soft-pastel', 'natural-light', 'vintage'],
    imageUrl: 'https://picsum.photos/seed/bohemian-maxi-skirt.jpg/600/800',
    productUrl: 'https://www.ssense.com/en-us/women/product/zimmermann/bohemian-maxi-skirt',
    price: 780,
    currency: 'USD',
  },
  {
    name: 'Tech Nylon Trench Coat',
    brand: 'Prada',
    type: 'outerwear',
    color: 'black',
    silhouette: 'longline',
    aestheticTags: ['futuristic', 'minimalist', 'urban', 'monochrome'],
    imageUrl: 'https://picsum.photos/seed/tech-nylon-trench-coat.jpg/600/800',
    productUrl: 'https://www.farfetch.com/shopping/women/prada-nylon-trench',
    price: 2450,
    currency: 'USD',
  },
  {
    name: 'Sculptural Gold Earrings',
    brand: 'Saint Laurent',
    type: 'accessory',
    color: 'gold',
    silhouette: 'statement',
    aestheticTags: ['luxury', 'editorial', 'avant-garde', 'high-contrast'],
    imageUrl: 'https://picsum.photos/seed/sculptural-gold-earrings.jpg/600/800',
    productUrl: 'https://www.ssense.com/en-us/women/product/saint-laurent/gold-earrings',
    price: 650,
    currency: 'USD',
  },
  {
    name: 'Monochrome Tailored Vest',
    brand: 'Toteme',
    type: 'top',
    color: 'ivory',
    silhouette: 'tailored',
    aestheticTags: ['minimalist', 'monochrome', 'editorial', 'luxury'],
    imageUrl: 'https://picsum.photos/seed/monochrome-tailored-vest.jpg/600/800',
    productUrl: 'https://www.farfetch.com/shopping/women/toteme-tailored-vest',
    price: 590,
    currency: 'USD',
  },
];
